version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=efrenn
      - POSTGRES_PASSWORD=ea12345
    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=djangodb
      - DATABASE_USER=efrenn
      - DATABASE_PASSWD=ea12345
      - DATABASE_HOST=db
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=efrenn@domain.com
      - PGADMIN_DEFAULT_PASSWORD=EA_2023!
    ports:
      - 5050:80
    volumes:
      - pgadmin:/srv/pgadmin
volumes:
  pgdata:
  pgadmin: